title: Svetek Help 
email: support@svetek.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Site description meta data for SEO.
#  Multiline example.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: pmarsceill/just-the-docs
#remote_theme: svrooij/just-the-docs@relative-everything

# Build settings
theme: "just-the-docs"
# plugins:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
# color_scheme: dark

# Google Analytics Tracking
# ga_tracking: UA-5555555-55
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

search_enabled: true
# logo: "/assets/images/just-the-docs.png"
gh_edit_link: false
aux_links:
  "Back to site":
    - "//www.svetek.com"
aux_links_new_tab: true
